WebApplication1616/Controllers/CheckBoxController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1616.Models;
using WebApplication1616.Controllers;
using WebApplication1616.BusinessLogic_bl;
namespace WebApplication1616.Controllers
{
    public class CheckBoxController : Controller
    {
        [HttpGet]

        public IActionResult Register()
        {
            return View();
        }
        [HttpGet]
        public IActionResult login2()
        {
            return View();
        }


      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(TASK1 obj)
        {
            if (ModelState.IsValid)
            {
                bool res = CheckBoxCURD.Data(obj);
                if (res == true)
                {
                    return View("Register");
                }
                else
                {
                    return View();
                }

            }
            else
            {
                return View();
            }

        }
        public IActionResult homepage()
        {
            return View();

        }
    }
}

WebApplication1616/Views/CheckBox/Register.cshtml
@using WebApplication1616.Models
@model TASK1

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Bootstrap 5 Forgot Password</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="signup-form mt-5 border p-4 bg-light shadow">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <h4 class="mb-5 text-secondary">Create Your Account</h4>
                        <div class="row">

                            <div class="mb-3 col-md-6">
                                <label> Name<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder="Enter Name" })
                                @Html.ValidationMessageFor(model => model.Name,"",new{@class="text-danger"})
                            </div>
                            <div class="mb-3 col-md-12">
                                <label>EmailID<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.Emailid, new { @class = "form-control", placeholder="Enter EmailID" })
                                @Html.ValidationMessageFor(model => model.Emailid,"",new{@class="text-danger"})
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>Password<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.password, new { @class = "form-control", placeholder="Enter Password" })
                                @Html.ValidationMessageFor(model => model.password,"",new{@class="text-danger"})
                            </div>


                            <div class="mb-3 col-md-12">
                                <label>Gender<span class="text-danger">*</span></label>
                                @Html.RadioButtonFor(model => model.Gender, "Male", new { id = "male-true"  })
                                @Html.Label("male-true", "Male")
                                @Html.RadioButtonFor(model => model.Gender, "Female", new { id = "female-true"})
                                @Html.Label("female-true", "Female")
                                @Html.ValidationMessageFor(model=>model.Gender,"",new {@class="text-danger"})
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>Department<span class="text-danger">*</span></label><br />


                                <input type="checkbox" class="specialization" id="civil" name="specialization[]" value="civil">civil<br />
                                <input type="checkbox" class="specialization" id="EEE" name="specialization[]" value="BTech">EEE<br />
                                <input type="checkbox" class="specialization" id="Mech" name="specialization[]" value="MTech">MECH<br />
                                <input type="checkbox" class="specialization" id="CSE" name="specialization[]" value="MCA">CSE<br />
                                <input type="checkbox" class="specialization" id="ECE" name="specialization[]" value="ECE">ECE<br />
                                @Html.ValidationMessageFor(model=>model.Gender,"",new {@class="text-danger"})
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>College name<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.collegename, new { @class = "form-control", placeholder="Enter Fee" })
                                @Html.ValidationMessageFor(model=>model.collegename,"",new {@class="text-danger"})
                            </div>
                        </div>
                        <div class="mb-3 col-md-6">
                            <label>University <span class="text-danger">*</span></label><br />
                            <input type="checkbox" class="specialization" id="JNTUK" name="specialization[]" value="JNTUK">JNTUK<br />
                            <input type="checkbox" class="specialization" id="JNTUA" name="specialization[]" value="BTech">JNTUA<br />
                            @Html.ValidationMessageFor(model=>model.University,"",new {@class="text-danger"})
                        </div>
                        <div class="mb-3 col-md-6">
                            <label>location <span class="text-danger">*</span></label><br />
                            <input type="checkbox" class="specialization" id="HYD" name="specialization[]" value="HYD">HYD<br />
                            <input type="checkbox" class="specialization" id="vijayawada" name="specialization[]" value="vijayawad">vijayawad<br />
                            @Html.ValidationMessageFor(model=>model.location,"",new {@class="text-danger"})
                        </div>
                        <div class="col-md-4">
                            <p class="text-center mt-3 text-secondary">If you have account,  @Html.ActionLink("Login","login2","CheckBox")</p>
                        </div>
                        <div class="col-md-8">
                            <input type="submit" class="btn btn-primary float-end" value="Submit">
                        </div>

                        <div />
                    }
                </div>
            </div>
        </div>
    </div>

</body>
</html>

WebApplication1616/Views/CheckBox/homepage.cshtml
@using WebApplication1616.Models
@model TASK1
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> welcome to homepage</title>
</head>
<body>
    <h1>welcome to homepage</h1>
</body>
</html>

WebApplication1616/Views/CheckBox/login2.cshtml
@using WebApplication1616.Models
@model TASK1
using WebApplication1616.Controllers

<!DOCTYPE html>
<html lang="en">
<head>
    <title>How To Create Simple Login Form Design In Bootstrap 5</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://www.markuptag.com/bootstrap/5/css/bootstrap.min.css">
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="login-form bg-light mt-4 p-4 row g-3">
                    @using (Html.BeginForm())
                    {
                        <h4>Welcome Back</h4>
                        <div class="col-12">
                            <label>EMAILID</label>
                            @Html.TextBoxFor(model=>model.Emailid,new {htmlAttributeValue=new {@class="form-control"}})

                        </div>
                        <div class="col-12">
                            <label>Password</label>
                            @Html.TextBoxFor(model=>model.Gender,new{htmlAttributeValue=new{@class="form-control"}})

                        </div>
                        <div class="col-12">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="rememberMe">
                                <label class="form-check-label" for="rememberMe"> Remember me</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <input type="submit" value="submit" class="btn btn-dark float-end" />

                        </div>
                    }
                    <hr class="mt-4">
                    <div class="col-12">
                        <p class="text-center mb-0">Have not account yet? @Html.ActionLink("Login","login2","CheckBox")</p>
                    </div>
                    <div class="col-12">
                        <p class="text-center mb-0"> @Html.ActionLink("homepage","homepage","CheckBox")</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://www.markuptag.com/bootstrap/5/js/bootstrap.bundle.min.js"></script>
</body>
</html>