WebApplication1616/Controllers/DDLController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1616.Models;
using WebApplication1616.BusinessLogic_bl;

namespace WebApplication1616.Controllers
{
    public class DDLController : Controller
    {
        [HttpGet]
        public IActionResult ViewDropDownVal()
        {
            ViewBag.data = ddl_bl.PopulateData();
            return View();
        }
        [HttpPost]
        public IActionResult ViewDropDownVal(string x)
        {
            ViewBag.data = Request.Form["test"].ToString();
            return View();
        }

        [HttpGet]
        public IActionResult GetDataonDDL()
        {
            ViewBag.data = ddl_bl.PopulateData();
            return View();
        }
        [HttpPost]
        public IActionResult GetDataonDDL(string customers)
        {
            ViewData["Val"] = ddl_bl.GETProductListbyID(Request.Form["test"].ToString());
            ViewBag.data = ddl_bl.PopulateData();
            return View();
        }
    }
}

WebApplication1616/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Portfolio</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">ADMIN</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Gallery</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="jumbotron">
        <div class="container text-center">
            <h1>My Portfolio</h1>
            <p>Some text that represents "Me"...</p>
        </div>
    </div>

    <div class="container-fluid bg-3 text-center">
        <h3></h3><br>
        <div class="row">
            <div class="col-sm-3">
                <p> welcome,@Html.ActionLink("ADMINLOGIN","Login","STD")</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">

            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
        </div>
    </div>
    <br>

    <div class="container-fluid bg-3 text-center">
        <div class="row">
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
            <div class="col-sm-3">
                <p>Some text..</p>
                <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
            </div>
        </div>
    </div>
    <br>
    <br>
    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>
</body>
</html>

WebApplication1616/Views/Shared/_CHECKBOXLayout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PAVANPUPPALA1616</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>

                    WelcomeBack: @HttpContextAccessor.HttpContext.Session.GetString("UserName")
                    Login at : @HttpContextAccessor.HttpContext.Session.GetString("Time")


                    <li class="active"><a href="#"> @Html.ActionLink("ADMIN","ADMIN","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("LIBRARY","LIBRARY","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CONTACT","CONTACT","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CHECKBOX","CHECKBOX","STD")</a></li>
                      <li class="active"><a href="#"> @Html.ActionLink("DISPLAYDATA","DisplayData","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("OTPVARIFICATION","VerifyOtp","STD")</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    @Html.ActionLink("ADMIN","ADMIN","STD")
                    @Html.ActionLink("OTPVARIFICATION","VerifyOtp","STD")
                </ul>
            </div>
        </div>
    </nav>
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="navbar">WELCOME PAVANPUPPALA1616</h1>
            <p>Some text About "Me"...</p>
        </div>
    </div>
    <div class="container-fluid bg-3 text-center">
        <h3></h3><br>
        <div class="row">
            <div class="col-sm-3">
                <p> @Html.ActionLink("INSERTDATA","DESIGN","INSERTCHECKBOX")</p>
                <img src="https://365datascience.com/resources/blog/2017-11-SQL-insert-pic-min-1024x576.png" class="img-responsive" style="width:100%" alt="Image">

            </div>

            <div class="jumbotron">
                <div class="container text-center">
                    <h1 class="navbar">WELCOME PAVANPUPPALA1616</h1>
                    <p>Some text About "Me"...</p>
                </div>
            </div>

            <div class="container-fluid bg-3 text-center">
                <h3></h3><br>
                <div class="row">
                    <div class="col-sm-3">
                        <p> @Html.ActionLink("Login","Login","STD")</p>
                        <img src="https://image.shutterstock.com/shutterstock/photos/225749503/display_1500/stock-vector-member-login-flat-design-white-225749503.jpg" class="img-responsive" style="width:70%" alt="Image">

                    </div>
                    <div class="col-sm-3">
                        <p>@Html.ActionLink("Registration","REGISTER","STD") </p>
                        <img src="https://thumbs.dreamstime.com/b/registration-online-membership-network-internet-business-technology-concept-104512007.jpg" class="img-responsive" style="width:100%" alt="Image">
                    </div>
                    <div class="col-sm-3">
                        <p>STUDENT DATA</p>
                        <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                    </div>
                    <div class="col-sm-3">
                        <p>LIBRARY</p>
                        <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
                    </div>
                </div>
            </div>
            <br>


    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>

WebApplication1616/Views/Shared/_CONTACTLayout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PAVANPUPPALA1616</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">

                    <li class="active"><a href="#">Home</a></li>
                    WelcomeBack: @HttpContextAccessor.HttpContext.Session.GetString("UserName")
                    Login at : @HttpContextAccessor.HttpContext.Session.GetString("Time")

                    <li class="active"><a href="#"> @Html.ActionLink("ADMIN","ADMIN","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("LIBRARY","LIBRARY","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CONTACT","CONTACT","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CHECKBOX","CHECKBOX","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("OTPVARIFICATION","VerifyOtp","STD")</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    @Html.ActionLink("ADMIN","ADMIN","STD")
                </ul>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>
</body>
</html>

WebApplication1616/Views/Shared/_DISPLAYDATALayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PAVANPUPPALA1616</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>

                    <li class="active"><a href="#"> @Html.ActionLink("ADMIN","ADMIN","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("LIBRARY","LIBRARY","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CONTACT","CONTACT","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CHECKBOX","CHECKBOX","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("DISPLAYDATA","DISPLAYDATA","STD")</a></li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>DISPLAYDATA</a></li>
                  
                </ul>
            </div>
        </div>
    </nav>
   < div class="container-fluid bg-3 text-center">
    <h3>DisplayData</h3>
    <br>
    <div class="row">
        <div class="col-sm-3">
            <p>@Html.ActionLink("DISPLAYDATA","DISPLAYDATA","STD")</p>
            <img src="https://image.shutterstock.com/shutterstock/photos/225749503/display_1500/stock-vector-member-login-flat-design-white-225749503.jpg" class="img-responsive" style="width:70%" alt="Image">

        </div>
        <div class="col-sm-3">
            <p>@Html.ActionLink("Registration","REGISTER","STD") </p>
            <img src="https://thumbs.dreamstime.com/b/registration-online-membership-network-internet-business-technology-concept-104512007.jpg" class="img-responsive" style="width:100%" alt="Image">
        </div>
        <div class="col-sm-3">
            <p>STUDENT DATA</p>
            <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
        </div>
        <div class="col-sm-3">
            <p>LIBRARY</p>
            <img src="https://placehold.it/150x80?text=IMAGE" class="img-responsive" style="width:100%" alt="Image">
        </div>
    </div>
    </div>
    

    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>

WebApplication1616/Views/Shared/_LIBRARYLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PAVANPUPPALA1616</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>

                    <li class="active"><a href="#"> @Html.ActionLink("ADMIN","ADMIN","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("LIBRARY","LIBRARY","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CONTACT","CONTACT","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CHECKBOX","CHECKBOX","STD")</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    @Html.ActionLink("ADMIN","ADMIN","STD")
                </ul>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>
</body>
</html>

WebApplication1616/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1616</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1616.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1616</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1616 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1616/Views/Shared/_UserLayout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }
  </style>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PAVANPUPPALA1616</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    
                        WelcomeBack: @HttpContextAccessor.HttpContext.Session.GetString("UserName")
                        Login at : @HttpContextAccessor.HttpContext.Session.GetString("Time")
                    
                    </li>
                    <li class="active"><a href="#"> @Html.ActionLink("ADMIN","ADMIN","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("LIBRARY","LIBRARY","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CONTACT","CONTACT","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("CHECKBOX","CHECKBOX","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("DISPLAYDATA","DISPLAYDATA","STD")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("StoreData","StoreData","SecondExView")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("ExonViewData","ExonViewData","ExView")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("ViewData","ViewDataEx","ExView")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("DROPDOWN","ALERT","ALERTMSG")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("ORDERSDROPDOWM","OrdersDROPDOWN","OrdersDROPDOWN")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("WelcomeAlertMsg","HIMSG","ALERT")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("GetDataonDDL","GetDataCusid","GETDatabyCustomerID")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("ViewDropDownVal","ViewDropDownVal","DDL")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("DISPLAYODERSTABLE","GetDataonDDL","DDL")</a></li>
                    <li class="active"><a href="#"> @Html.ActionLink("OTPVARIFICATION","VerifyOtp","STD")</a></li>
                    <li class="active"><a href="#"> </a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    @Html.ActionLink("ADMIN","ADMIN","STD")
                    @Html.ActionLink("LOGOUT","LOGOUT","STD")
                   
                </ul>
            </div>
        </div>
    </nav>

    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="navbar">WELCOME PAVANPUPPALA1616</h1>
            <p>Some text About "Me"...</p>
        </div>
    </div>

    <div class="container-fluid bg-3 text-center">
        <h3></h3><br>
        <div class="row">
            <div class="col-sm-3">
                <p>  @Html.ActionLink("DISPLAYDATA","DISPLAYDATA","STD")</p>
                <img src="" class="img-responsive" style="width:70%" alt="Image">
              
            </div>
            <div class="col-sm-3">
                <p>@Html.ActionLink("Registration","REGISTER","STD") </p>
                <img src="" class="img-responsive" style="width:100%" alt="Image">
            </div>
            
        </div>
    </div>
    <br>

    

    <div>
        @RenderBody()
    </div>
    <footer class="container-fluid text-center">
        <p>Footer Text</p>
    </footer>

</body>
</html>