WebApplication1616/Models/Check.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;


namespace WebApplication1616.Models
{
    public class Check
    {

        public int REFID { get; set; }

        [Required(ErrorMessage = "Rollno is required*")]
        public string rollno { get; set; }

        [Required(ErrorMessage = "What's ur Name*")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string name { get; set; }

        [Required(ErrorMessage = "Email is required*")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Emailid { get; set; }


        [Required(ErrorMessage = "Please enter password*")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "Password \"{0}\" must have {2} character", MinimumLength = 8)]
        [RegularExpression(@"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$", ErrorMessage = "Password must contain: Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase Alphabet, 1 Number and 1 Special Character")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Select DOB*")]
        public DateTime DOB { get; set; }

        [Required(ErrorMessage = "Select option*")]
        public string GENDER { get; set; }

        [Required(ErrorMessage = "Mobile is required*")]
        [RegularExpression(@"\d{10}", ErrorMessage = "Please enter 10 digit Mobile No.")]
        public string MOBILE { get; set; }

        [Required(ErrorMessage = "Fee is required*")]
        [Range(typeof(int), "1000", "20000", ErrorMessage = "Fee can only be between 1000 and 20000")]
        public int FEE { get; set; }

        [Required(ErrorMessage = "Select role*")]
        public string Role { get; set; }



        [Required(ErrorMessage = "Select Branch*")]
        public string BRANCH { get; set; }
        public bool Status { get; set; }

        [Required(ErrorMessage = "Select Checkbox*")]

        public  bool Qualification { get; set; }
      
    }
}

WebApplication1616/Controllers/CheckController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1616.BusinessLogic_bl;
using WebApplication1616.Models;
using System;
namespace WebApplication1616.Controllers
{
    public class CheckController : Controller
    {
        [HttpGet]
        public IActionResult Checking()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checking(Check OBJ)
        {
            if (ModelState.IsValid)
            {
                bool res = Checking_bl.Insertdata(OBJ);
                if (res == true)
                {

                    return View("Homepage");
                }
                else
                {
                    return View(OBJ);
                }
            }
            else
            {
                return View(OBJ);
            }
        }
        public IActionResult Homepage()
        {
            return View();
        }
    }
}

WebApplication1616/Views/Check/Checking.cshtml
@using WebApplication1616.Models
@model Check
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>REGISTER</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://www.markuptag.com/bootstrap/5/css/bootstrap.min.css">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>



</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="signup-form mt-5 border p-4 bg-light shadow">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <h4 class="mb-5 text-secondary">Create Your Account</h4>
                        <div class="row">
                            <div class="mb-3 col-md-6">
                                <label>RollNo<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.rollno, new { @class = "form-control", placeholder="Enter Roll No" })
                                @Html.ValidationMessageFor(model => model.rollno, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label> Name<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.name, new { @class = "form-control", placeholder="Enter Name" })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>EmailID<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.Emailid, new { @class = "form-control", placeholder="Enter EmailID" })
                                @Html.ValidationMessageFor(model => model.Emailid, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>Password<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.Password, new { @class = "form-control", placeholder="Enter Password" })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>

                            <div class="mb-3 col-md-6">
                                <label>DOB<span class="text-danger">*</span></label>
                                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control input-md", @placeholder = "Name"} })
                                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-12">
                                <label>Gender<span class="text-danger">*</span></label>
                                @Html.RadioButtonFor(model => model.GENDER, "MALE", new { id = "male-true"  })
                                @Html.Label("male-true", "Male")
                                @Html.RadioButtonFor(model => model.GENDER, "FEMALE", new { id = "female-true"})
                                @Html.Label("female-true", "Female")
                                @Html.ValidationMessageFor(model => model.GENDER, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>Mobile<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.MOBILE, new { @class = "form-control", placeholder="Enter Mobile" })
                                @Html.ValidationMessageFor(model => model.MOBILE, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>Fee Details<span class="text-danger">*</span></label>
                                @Html.TextBoxFor(model => model.FEE, new { @class = "form-control", placeholder="Enter Fee" })
                                @Html.ValidationMessageFor(model => model.FEE, "", new { @class = "text-danger" })
                            </div>
                            <div class="mb-3 col-md-6">
                                <label>ROLE<span class="text-danger">*</span></label>
                                @Html.DropDownListFor(model => model.Role, new List<SelectListItem> {
                            new SelectListItem { Text="--Select--",Value="--select--"},
                            new SelectListItem { Text="STUDENT",Value="STUDENT"},
                            new SelectListItem { Text="PRINCIPLE",Value="PRINCIPLE"},
                            new SelectListItem { Text="STAFF",Value="STAFF"}

                            }, new { @class = "form-control" })
                           <div class="mb-3 col-md-6">
                                    <label>Branch<span class="text-danger">*</span></label>
                                    @Html.DropDownListFor(model => model.BRANCH, new List<SelectListItem> {
                                new SelectListItem { Text="--Select--",Value="0"},
                                new SelectListItem { Text="CSE",Value="CSE"},
                                new SelectListItem { Text="EEE",Value="EEE"},
                                new SelectListItem { Text="Mech",Value="Mech"},
                                new SelectListItem { Text="IT",Value="IT"},
                                new SelectListItem { Text="Civil",Value="Civil"}
                                }, new { @class = "form-control" })
                                </div>
                                <div class="mb-3 col-md-6">
                                    <label>Status<span class="text-danger">*</span></label>
                                    @Html.DropDownListFor(m => m.Status, new List<SelectListItem>
                                { new SelectListItem{Text="--Select--", Value="0"},
                                new SelectListItem{Text="Active", Value="True"},
                                new SelectListItem{Text="InActive", Value="False"}
                                }, new { @class = "form-control" })
                                </div>
                                <div>
                                    <label>Qualification<span class="text-danger">*</span></label>
                                    @Html.CheckBoxFor(model=>model.Qualification,new { @id1 = "BTECH-true"  })
                                    @Html.Label("BTECH-true", "BTECH")
                                    @Html.CheckBoxFor(model=>model.Qualification, new { @id2 = "MTECH-true"  })
                                    @Html.Label("MTECH-true", "MTECH")
                                    @Html.CheckBoxFor(model=>model.Qualification, new { @id3 = "DRGREE-true"  })
                                    @Html.Label("DEGREE-true", "DEGREE")
                                </div>
                                <div class="col-md-7">
                                    <p class="text-center mt-3 text-secondary">If you have account,  @Html.ActionLink("login","Homepage","Check")</p>
                                </div>
                                <div class="col-md-5">
                                    <input type="submit" class="btn btn-primary float-end" value="Submit"
                                       @Html.ActionLink("Homepage","Check")>
                                </div>
                            </div>
                        </div>
                      }
                      </div>
                      </body>
                      </html>

WebApplication1616/Views/Check/Homepage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Homepage</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>